#!/usr/bin/env bash

# For generation of .csr and .key file. 
#For generation script only asks for OU, CN, DNS(array) and IP(array)

### Config temp write
echo "[req]
default_bits = 2048
prompt = no
default_md = sha512
req_extensions = req_ext
distinguished_name = dn

[ dn ]
C=<YOUR COUNTRY>
ST=<YOUR STATE>
L=<YOUR CITY>
O=<YOUR ORGANIZATION>" > config_temp

### Check OU
read -rp "Enter OU: " OU
while [ -z "$OU" ] 
do
    read -rp "Enter NOT EMPTY OU: " OU
done
echo "OU=$OU" >> config_temp

echo "emailAddress=<YOUR EMAIL>" >> config_temp

### Check CN
read -rp "Enter CN: " CN
while [ -z "$CN" ] 
do
    read -rp "Enter NOT EMPTY CN: " CN
done
echo "CN = $CN" >> config_temp

echo "
[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]" >> config_temp

### Check DNS
COUNT_DNS=1
DNS_ARRAY=()

read -rp "DNS.1 = $CN, press ENTER to accept OR enter NEW value: " CURRENT_DNS
if [ -z "$CURRENT_DNS" ]; then
    DNS_ARRAY+=("$CN")
else
    DNS_ARRAY+=("$CURRENT_DNS")
fi

ANOTHER_DNS=1
while [ $ANOTHER_DNS -eq 1 ]
do
    read -rp "Do you need another DNS(y,N): " DNS_OPT
    if [[ "$DNS_OPT" =~ ^("y"|"Y")$ ]]; then
        ((COUNT_DNS++))
        
        read -rp "Enter DNS_$COUNT_DNS: " CURRENT_DNS
        while [ -z "$CURRENT_DNS" ]
        do
            read -rp "Enter not EMPTY DNS_$COUNT_DNS: " CURRENT_DNS
        done
        DNS_ARRAY+=("$CURRENT_DNS")
    else ANOTHER_DNS=0
    fi
done

for i in $(/usr/bin/seq 0 $(("$COUNT_DNS" - 1)))
do
    echo "DNS.$(("$i"+1)) = ${DNS_ARRAY[$i]}" >> config_temp
done

### Check IP
COUNT_IP=1
IP_ARRAY=()

read -rp "Enter IP: " CURRENT_IP
while [ -z "$CURRENT_IP" ]
do
    read -rp "Enter not EMPTY IP: " CURRENT_IP
done
IP_ARRAY+=("$CURRENT_IP")

ANOTHER_IP=1
while [ $ANOTHER_IP -eq 1 ]
do
    read -rp "Do you need another IP(y,N): " IP_OPT
    if [[ "$IP_OPT" =~ ^("y"|"Y")$ ]]; then
        ((COUNT_IP++))
        
        read -rp "Enter IP_$COUNT_IP: " CURRENT_IP
        while [ -z "$CURRENT_IP" ]
        do
            read -rp "Enter not EMPTY IP_$COUNT_IP: " CURRENT_IP
        done
        IP_ARRAY+=("$CURRENT_IP")
    else ANOTHER_IP=0
    fi
done

for i in $(/usr/bin/seq 0 $(("$COUNT_IP" - 1)))
do
    echo "IP.$(("$i"+1)) = ${IP_ARRAY[$i]}" >> config_temp
done

### Create DIR
echo "Creating dir for CN"
if [ -d "$CN" ]; then
    echo "Request dir is already created, skipping..."
else
    if mkdir "$CN"; then
        echo "Dir for request has been created"
    else
        echo "FAILED: to create request dir"
        exit 1
    fi
fi

### Execute reques and get csr and key
if /usr/bin/openssl req -new -sha512 -nodes -out "$CN"/"$CN".csr -newkey rsa:2048 -keyout "$CN"/"$CN".key -config config_temp; then
    /usr/bin/chmod 777 "$CN"/*
    /usr/bin/rm -f config_temp
    echo "SUCCESS!"

else "FAILED!"
fi
